const documentsData = [
  {
    documents: [
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
    ],
  },
  {
    documents: [
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Вторая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Вторая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Вторая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Вторая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Вторая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
    ],
  },
  {
    documents: [
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Четвертая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Первая редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: " Вторая редакция проекта стандарта",
        type: "docx",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
      {
        name: "Третья редакция проекта стандарта",
        type: "pdf",
        file_name: "Первая ред проекта ГОСТ Р ЗиС Методика",
        doc_link: "https://www.google.com",
        file: "../files/file.txt",
        status: "40.00 Первая редакция стандарта",
        action_link: "https://www.google.com",
        action: "Подать замечание",
      },
    ],
  }
];
