const organizationsList = [
  {
    id: 0,
    write_to_link:"https://www.google.com",
    full_name: "Организация 1",
    organization_link:"https://www.google.com",
    red_name: "Орг 1",
    address: "Адрес организации 1",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "4",
    ost: "",
    candidate: "",
  },
  {
    id: 1,
    write_to_link:"https://www.google.com",
    full_name: "Организация 2",
    organization_link:"https://www.google.com",
    red_name: "Орг 2",
    address: "Адрес организации 2",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "5",
    ost: "",
    candidate: "",
  },  {
    id: 2,
    write_to_link:"https://www.google.com",
    full_name: " ",
    organization_link:"https://www.google.com",
    red_name: "Орг 3",
    address: "Адрес организации 3",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "2",
    ost: "",
    candidate: "",
  },  {
    id: 3,
    write_to_link:"https://www.google.com",
    full_name: "Организация 4",
    organization_link:"https://www.google.com",
    red_name: "Орг 4",
    address: "Адрес организации 4",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "9",
    ost: "",
    candidate: "",
  }, {
    id: 0,
    write_to_link:"https://www.google.com",
    full_name: "Организация 1",
    organization_link:"https://www.google.com",
    red_name: "Орг 1",
    address: "Адрес организации 1",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "4",
    ost: "",
    candidate: "",
  },
  {
    id: 1,
    write_to_link:"https://www.google.com",
    full_name: "Организация 2",
    organization_link:"https://www.google.com",
    red_name: "Орг 2",
    address: "Адрес организации 2",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "5",
    ost: "",
    candidate: "",
  },  {
    id: 2,
    write_to_link:"https://www.google.com",
    full_name: "Организация 3",
    organization_link:"https://www.google.com",
    red_name: "Орг 3",
    address: "Адрес организации 3",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "2",
    ost: "",
    candidate: "",
  },  {
    id: 3,
    write_to_link:"https://www.google.com",
    full_name: "Организация 4",
    organization_link:"https://www.google.com",
    red_name: "Орг 4",
    address: "Адрес организации 4",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "9",
    ost: "",
    candidate: "",
  }, {
    id: 0,
    write_to_link:"https://www.google.com",
    full_name: "Организация 1",
    organization_link:"https://www.google.com",
    red_name: "Орг 1",
    address: "Адрес организации 1",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "4",
    ost: "",
    candidate: "",
  },
  {
    id: 1,
    write_to_link:"https://www.google.com",
    full_name: "Организация 2",
    organization_link:"https://www.google.com",
    red_name: "Орг 2",
    address: "Адрес организации 2",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "5",
    ost: "",
    candidate: "",
  },  {
    id: 2,
    write_to_link:"https://www.google.com",
    full_name: "Организация 3",
    organization_link:"https://www.google.com",
    red_name: "Орг 3",
    address: "Адрес организации 3",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "2",
    ost: "",
    candidate: "",
  },  {
    id: 3,
    write_to_link:"https://www.google.com",
    full_name: "Организация 4",
    organization_link:"https://www.google.com",
    red_name: "Орг 4",
    address: "Адрес организации 4",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "9",
    ost: "",
    candidate: "",
  }, {
    id: 0,
    write_to_link:"https://www.google.com",
    full_name: "Организация 1",
    organization_link:"https://www.google.com",
    red_name: "Орг 1",
    address: "Адрес организации 1",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "4",
    ost: "",
    candidate: "",
  },
  {
    id: 1,
    write_to_link:"https://www.google.com",
    full_name: "Организация 2",
    organization_link:"https://www.google.com",
    red_name: "Орг 2",
    address: "Адрес организации 2",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "5",
    ost: "",
    candidate: "",
  },  {
    id: 2,
    write_to_link:"https://www.google.com",
    full_name: "Организация 3",
    organization_link:"https://www.google.com",
    red_name: "Орг 3",
    address: "Адрес организации 3",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "2",
    ost: "",
    candidate: "",
  },  {
    id: 3,
    write_to_link:"https://www.google.com",
    full_name: "Организация 4",
    organization_link:"https://www.google.com",
    red_name: "Орг 4",
    address: "Адрес организации 4",
    phone_number: "+7 (800) 123-45-65",
    fax: "+7 (800) 123-45-65",
    email: "examplemail@gmail.com",
    site: "google.com",
    site_link: "https://www.google.com",
    sequence: "9",
    ost: "",
    candidate: "",
  },
];
